[build]
  image = "ubuntu-24.04"

[build.environment]
  NODE_VERSION = "24.9.0"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-emails"
  [plugins.inputs]
    directory = "emails"

[functions]
  node_bundler = "esbuild"
